# Generated by Django 4.2.20 on 2025-04-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_user_alter_review_user_name'),
        ('reviews', 'migrate_usernames'),
    ]

    operations = [
    ]
